version: "2"

services:
  app:
    build: .
    ports:
      - 3000:8080
      - 8080:80
    volumes:
      - .:/app
    environment:
      SERVICES: webservices:_:webservices:3000
      HEALTHCHECK_PORT: 8080
      PROXY_PORT: 80
  webservices:
    image: renegare/test-api:673d917
    networks:
      default:
        ipv4_address: 172.16.238.20

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
      com.docker.network.bridge.enable_ip_masquerade: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
